### ISSUE TITLE
Possible bug in _liu_mod

### ISSUE THREAD

**Issue by mkerin** [limix/chiscore#1]
Hi,

Just want to query line 61 in chiscore/_liu.py. The [Liu paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.421.5737&rep=rep1&type=pdf) seems to suggest that line 61 should be

```
l = 1 / (s1 ** 2)
```
instead of
```
l = 1 / s2
```

I'd be grateful if you could clarify if this is correct.

-----

Looking again you also seem to assume (lines 64 & 66) that delta = 0 in the `s1 ** 2 > s2` case. Is this an intentional approximation?

**Comment by horta** [comment]
Hi @mkerin , sorry for the long delay.

You are correct that it should be ``l = 1 / s2``. I've fixed it now. But I also noticed that ``1 / (s1 ** 2)`` would be very close to ``l = 1 / s2`` when ``s1**2 > s2`` anyway.

Regarding ``delta=0``, this is actually the optimal solution for ``delta``. So there is no approximation here.

I've just released the 0.1.0 version with a better documentation and fixes regarding Lius' method.
